service:
  name: todo-serverless-restful-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2

functions:
  read:
    handler: todo.read
    events:
      - http:
          method: get
          path: todo
  create:
    handler: todo.create
    events:
      - http:
          method: post
          path: todo
  update:
    handler: todo.update
    events:
      - http:
          method: put
          path: todo
  delete:
    handler: todo.remove
    events:
      - http:
          method: delete
          path: todo
